// Generated by tools/build.mjs. Edit data/, not this file.
globalThis.styleHub = {
  "title": "Style inspiration",
  "collections": [
    {
      "id": "minimalist-machine",
      "title": "Minimalist Machine",
      "href": "minimalist-machine.html",
      "moods": [
        "precise",
        "utilitarian",
        "quiet",
        "technical"
      ],
      "status": "seed"
    },
    {
      "id": "international-typographic-style",
      "title": "International Typographic Style",
      "href": "international-typographic-style.html",
      "moods": [
        "objective",
        "rational",
        "clear",
        "restrained"
      ],
      "status": "pilot"
    },
    {
      "id": "bauhaus",
      "title": "Bauhaus",
      "href": "bauhaus.html",
      "moods": [
        "constructive",
        "bold",
        "geometric",
        "experimental"
      ],
      "status": "pilot"
    },
    {
      "id": "memphis",
      "title": "Memphis",
      "href": "memphis.html",
      "moods": [
        "playful",
        "loud",
        "irreverent",
        "postmodern"
      ],
      "status": "pilot"
    },
    {
      "id": "frutiger-aero",
      "title": "Frutiger Aero",
      "href": "frutiger-aero.html",
      "moods": [
        "optimistic",
        "fresh",
        "glossy",
        "eco-technological"
      ],
      "status": "pilot"
    },
    {
      "id": "neo-brutalism",
      "title": "Neo-brutalism",
      "href": "neo-brutalism.html",
      "moods": [
        "direct",
        "loud",
        "playful",
        "raw"
      ],
      "status": "pilot"
    }
  ],
  "references": [
    {
      "id": "detail-blog",
      "title": "Detail blog",
      "href": "references/detail-blog.html",
      "type": "website",
      "medium": "website",
      "styles": [
        "minimalist-machine"
      ],
      "status": "observed"
    },
    {
      "id": "pure-data",
      "title": "Pure Data",
      "href": "references/pure-data.html",
      "type": "product",
      "medium": "software",
      "styles": [
        "minimalist-machine"
      ],
      "status": "documented"
    },
    {
      "id": "puredata-site",
      "title": "Pure Data community site",
      "href": "references/puredata-site.html",
      "type": "website",
      "medium": "website",
      "styles": [
        "minimalist-machine"
      ],
      "status": "pending"
    },
    {
      "id": "malewicz-neubrutalism-article-2022",
      "title": "“Neubrutalism is taking over the web”",
      "href": "references/malewicz-neubrutalism-article-2022.html",
      "type": "website",
      "medium": "editorial",
      "styles": [
        "neo-brutalism"
      ],
      "status": "documented"
    },
    {
      "id": "akzidenz-grotesk-typeface",
      "title": "Akzidenz-Grotesk typeface",
      "href": "references/akzidenz-grotesk-typeface.html",
      "type": "object",
      "medium": "typeface",
      "styles": [
        "international-typographic-style"
      ],
      "status": "observed"
    },
    {
      "id": "bauhaus-building-dessau",
      "title": "Bauhaus building, Dessau",
      "href": "references/bauhaus-building-dessau.html",
      "type": "object",
      "medium": "architecture",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "bauhaus-signet-1922",
      "title": "Bauhaus signet",
      "href": "references/bauhaus-signet-1922.html",
      "type": "image",
      "medium": "other",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "wagenfeld-jucker-table-lamp",
      "title": "Bauhaus table lamp (Wagenfeld and Jucker)",
      "href": "references/wagenfeld-jucker-table-lamp.html",
      "type": "object",
      "medium": "product",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "bauhausbucher-8-malerei-fotografie-film",
      "title": "Bauhausbücher 8: Malerei, Fotografie, Film",
      "href": "references/bauhausbucher-8-malerei-fotografie-film.html",
      "type": "print",
      "medium": "book",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "shire-bel-air-chair-1982",
      "title": "Bel Air chair",
      "href": "references/shire-bel-air-chair-1982.html",
      "type": "object",
      "medium": "furniture",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "bliss-windows-xp-wallpaper-1996",
      "title": "Bliss",
      "href": "references/bliss-windows-xp-wallpaper-1996.html",
      "type": "image",
      "medium": "photograph",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "brutalist-websites-directory",
      "title": "Brutalist Websites",
      "href": "references/brutalist-websites-directory.html",
      "type": "website",
      "medium": "website",
      "styles": [
        "neo-brutalism"
      ],
      "status": "documented"
    },
    {
      "id": "sottsass-carlton-room-divider-1981",
      "title": "Carlton room divider",
      "href": "references/sottsass-carlton-room-divider-1981.html",
      "type": "object",
      "medium": "furniture",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "sottsass-casablanca-sideboard-1981",
      "title": "Casablanca sideboard",
      "href": "references/sottsass-casablanca-sideboard-1981.html",
      "type": "object",
      "medium": "furniture",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "crystal-clear-icons-everaldo-coelho",
      "title": "Crystal Clear icons",
      "href": "references/crystal-clear-icons-everaldo-coelho.html",
      "type": "image",
      "medium": "illustration",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "der-film-poster-1960",
      "title": "Der Film exhibition poster",
      "href": "references/der-film-poster-1960.html",
      "type": "print",
      "medium": "poster",
      "styles": [
        "international-typographic-style"
      ],
      "status": "observed"
    },
    {
      "id": "asadal-earth-and-city-10-2007",
      "title": "Earth and City 10 (Expression of Ideas)",
      "href": "references/asadal-earth-and-city-10-2007.html",
      "type": "image",
      "medium": "illustration",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "envato-neo-brutalism-trend-2023",
      "title": "Envato, “Trend Deep Dive: Neo-brutalism”",
      "href": "references/envato-neo-brutalism-trend-2023.html",
      "type": "website",
      "medium": "editorial",
      "styles": [
        "neo-brutalism"
      ],
      "status": "documented"
    },
    {
      "id": "figma-website-2022",
      "title": "Figma marketing website, c. 2022",
      "href": "references/figma-website-2022.html",
      "type": "website",
      "medium": "website",
      "styles": [
        "neo-brutalism"
      ],
      "status": "documented"
    },
    {
      "id": "de-lucchi-first-chair-1983",
      "title": "First chair",
      "href": "references/de-lucchi-first-chair-1983.html",
      "type": "object",
      "medium": "furniture",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "snowball-fractal-design-system",
      "title": "Fractal, Snowball’s design system",
      "href": "references/snowball-fractal-design-system.html",
      "type": "product",
      "medium": "software",
      "styles": [
        "neo-brutalism"
      ],
      "status": "observed"
    },
    {
      "id": "frutiger-typeface-1976",
      "title": "Frutiger typeface",
      "href": "references/frutiger-typeface-1976.html",
      "type": "object",
      "medium": "typeface",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "du-pasquier-gabon-textile-1982",
      "title": "Gabon textile samples",
      "href": "references/du-pasquier-gabon-textile-1982.html",
      "type": "object",
      "medium": "textile",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "giselle-poster-1959",
      "title": "Giselle poster, Basler Freilichtspiele",
      "href": "references/giselle-poster-1959.html",
      "type": "print",
      "medium": "poster",
      "styles": [
        "international-typographic-style"
      ],
      "status": "observed"
    },
    {
      "id": "grid-systems-in-graphic-design-1981",
      "title": "Grid Systems in Graphic Design",
      "href": "references/grid-systems-in-graphic-design-1981.html",
      "type": "print",
      "medium": "book",
      "styles": [
        "international-typographic-style"
      ],
      "status": "observed"
    },
    {
      "id": "gumroad-website-redesign-2021",
      "title": "Gumroad website and brand, 2021",
      "href": "references/gumroad-website-redesign-2021.html",
      "type": "website",
      "medium": "website",
      "styles": [
        "neo-brutalism"
      ],
      "status": "observed"
    },
    {
      "id": "stolzl-five-choirs-design",
      "title": "Gunta Stölzl, design for the wall hanging “Fünf Chöre”",
      "href": "references/stolzl-five-choirs-design.html",
      "type": "image",
      "medium": "textile",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "helvetica-typeface",
      "title": "Helvetica typeface",
      "href": "references/helvetica-typeface.html",
      "type": "object",
      "medium": "typeface",
      "styles": [
        "international-typographic-style"
      ],
      "status": "observed"
    },
    {
      "id": "bayer-universal-type-study",
      "title": "Herbert Bayer, Research in Development of Universal Type",
      "href": "references/bayer-universal-type-study.html",
      "type": "image",
      "medium": "typeface",
      "styles": [
        "bauhaus"
      ],
      "status": "documented"
    },
    {
      "id": "kandinsky-bauhaus-exhibition-postcard-1923",
      "title": "Kandinsky’s postcard for the 1923 Bauhaus exhibition",
      "href": "references/kandinsky-bauhaus-exhibition-postcard-1923.html",
      "type": "print",
      "medium": "other",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "capital-magazine-layout-grid-gerstner",
      "title": "Karl Gerstner’s grid for Capital",
      "href": "references/capital-magazine-layout-grid-gerstner.html",
      "type": "image",
      "medium": "editorial",
      "styles": [
        "international-typographic-style"
      ],
      "status": "documented"
    },
    {
      "id": "kde-plasma-4-desktop",
      "title": "KDE Plasma 4 desktop",
      "href": "references/kde-plasma-4-desktop.html",
      "type": "product",
      "medium": "operating-system",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "mac-os-x-aqua-interface",
      "title": "Mac OS X Aqua interface",
      "href": "references/mac-os-x-aqua-interface.html",
      "type": "product",
      "medium": "operating-system",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "breuer-club-chair-b3",
      "title": "Marcel Breuer, club chair B 3 (“Wassily”)",
      "href": "references/breuer-club-chair-b3.html",
      "type": "object",
      "medium": "furniture",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "brandt-tea-infuser-mt-49",
      "title": "Marianne Brandt, tea infuser MT 49",
      "href": "references/brandt-tea-infuser-mt-49.html",
      "type": "object",
      "medium": "product",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "radl-memphis-logotype-drawing-1982",
      "title": "Memphis logotype drawing",
      "href": "references/radl-memphis-logotype-drawing-1982.html",
      "type": "image",
      "medium": "other",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "radl-memphis-milano-leaflet-1983",
      "title": "Memphis Milano leaflet",
      "href": "references/radl-memphis-milano-leaflet-1983.html",
      "type": "print",
      "medium": "editorial",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "memphis-printed-cotton-swatch-1985",
      "title": "Memphis printed cotton swatch card",
      "href": "references/memphis-printed-cotton-swatch-1985.html",
      "type": "object",
      "medium": "textile",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "munich-1972-olympic-pictograms",
      "title": "Munich 1972 Olympic pictograms",
      "href": "references/munich-1972-olympic-pictograms.html",
      "type": "object",
      "medium": "signage",
      "styles": [
        "international-typographic-style"
      ],
      "status": "observed"
    },
    {
      "id": "neobrutalism-components-library",
      "title": "Neobrutalism components",
      "href": "references/neobrutalism-components-library.html",
      "type": "product",
      "medium": "software",
      "styles": [
        "neo-brutalism"
      ],
      "status": "observed"
    },
    {
      "id": "neobrutalism-swiftui-package",
      "title": "NeoBrutalism for SwiftUI",
      "href": "references/neobrutalism-swiftui-package.html",
      "type": "product",
      "medium": "software",
      "styles": [
        "neo-brutalism"
      ],
      "status": "observed"
    },
    {
      "id": "neubrutalism-ui-flutter-package",
      "title": "neubrutalism_ui for Flutter",
      "href": "references/neubrutalism-ui-flutter-package.html",
      "type": "product",
      "medium": "software",
      "styles": [
        "neo-brutalism"
      ],
      "status": "observed"
    },
    {
      "id": "neue-grafik-journal-1958-1965",
      "title": "Neue Grafik journal",
      "href": "references/neue-grafik-journal-1958-1965.html",
      "type": "print",
      "medium": "editorial",
      "styles": [
        "international-typographic-style"
      ],
      "status": "observed"
    },
    {
      "id": "nngroup-neobrutalism-article-2025",
      "title": "NN/g, “Neobrutalism: Definition and Best Practices”",
      "href": "references/nngroup-neobrutalism-article-2025.html",
      "type": "website",
      "medium": "editorial",
      "styles": [
        "neo-brutalism"
      ],
      "status": "documented"
    },
    {
      "id": "nycta-graphics-standards-manual-1970",
      "title": "NYCTA Graphics Standards Manual",
      "href": "references/nycta-graphics-standards-manual-1970.html",
      "type": "print",
      "medium": "signage",
      "styles": [
        "international-typographic-style"
      ],
      "status": "documented"
    },
    {
      "id": "offset-bauhaus-issue-1926",
      "title": "Offset: Buch und Werbekunst, Bauhaus issue",
      "href": "references/offset-bauhaus-issue-1926.html",
      "type": "print",
      "medium": "editorial",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "poste-italiane-agenzia-62-iosa-ghini-2007",
      "title": "Poste Italiane Agenzia 62, Rome",
      "href": "references/poste-italiane-agenzia-62-iosa-ghini-2007.html",
      "type": "object",
      "medium": "architecture",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "bauhaus-exhibition-poster-1923",
      "title": "Poster for the 1923 Bauhaus exhibition",
      "href": "references/bauhaus-exhibition-poster-1923.html",
      "type": "print",
      "medium": "poster",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "retroui-component-library",
      "title": "RetroUI (neobrutalism/neobrutalism)",
      "href": "references/retroui-component-library.html",
      "type": "product",
      "medium": "software",
      "styles": [
        "neo-brutalism"
      ],
      "status": "observed"
    },
    {
      "id": "segoe-ui-typeface",
      "title": "Segoe UI typeface",
      "href": "references/segoe-ui-typeface.html",
      "type": "object",
      "medium": "typeface",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "staatliches-bauhaus-in-weimar-1919-1923",
      "title": "Staatliches Bauhaus in Weimar 1919–1923",
      "href": "references/staatliches-bauhaus-in-weimar-1919-1923.html",
      "type": "print",
      "medium": "book",
      "styles": [
        "bauhaus"
      ],
      "status": "observed"
    },
    {
      "id": "bedin-super-lamp-1981",
      "title": "Super lamp",
      "href": "references/bedin-super-lamp-1981.html",
      "type": "object",
      "medium": "product",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "umeda-tawaraya-colour-tests-1981",
      "title": "Tawaraya colour tests",
      "href": "references/umeda-tawaraya-colour-tests-1981.html",
      "type": "image",
      "medium": "other",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "typographie-emil-ruder-1967",
      "title": "Typographie, by Emil Ruder",
      "href": "references/typographie-emil-ruder-1967.html",
      "type": "print",
      "medium": "book",
      "styles": [
        "international-typographic-style"
      ],
      "status": "observed"
    },
    {
      "id": "univers-typeface",
      "title": "Univers typeface",
      "href": "references/univers-typeface.html",
      "type": "object",
      "medium": "typeface",
      "styles": [
        "international-typographic-style"
      ],
      "status": "observed"
    },
    {
      "id": "zanini-victoria-vase-1982",
      "title": "Victoria vase",
      "href": "references/zanini-victoria-vase-1982.html",
      "type": "object",
      "medium": "product",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "sowden-view-of-an-interior-1983",
      "title": "View of an Interior",
      "href": "references/sowden-view-of-an-interior-1983.html",
      "type": "print",
      "medium": "illustration",
      "styles": [
        "memphis"
      ],
      "status": "observed"
    },
    {
      "id": "wii-menu-2006",
      "title": "Wii Menu",
      "href": "references/wii-menu-2006.html",
      "type": "product",
      "medium": "software",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "windows-7-aero-interface",
      "title": "Windows 7 Aero interface and default wallpaper",
      "href": "references/windows-7-aero-interface.html",
      "type": "product",
      "medium": "operating-system",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    },
    {
      "id": "windows-vista-aero-interface",
      "title": "Windows Vista Aero interface",
      "href": "references/windows-vista-aero-interface.html",
      "type": "product",
      "medium": "operating-system",
      "styles": [
        "frutiger-aero"
      ],
      "status": "observed"
    }
  ]
};
